name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Deploy to Droplet
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_HOST }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Create the app directory if it doesn't exist
          mkdir -p /home/chron-yt-backend
          cd /home/chron-yt-backend
          
          # Copy the app files to the directory
          scp -r . ubuntu@${{ secrets.DROPLET_HOST }}:/home/chron-yt-backend
          
          # Pull the latest code
          git pull origin main
          
          # Install dependencies
          npm install --production
          
          # Start the app with PM2
          pm2 start app.js --name chron-yt-backend
